### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by veelenga** [lbguilherme/os-crystal#3]
Hey @lbguilherme. Thanks for a great proof on concept.

Sorry, I am not an expert in kernel development, but I just tried that and can't compile on OS X:

```sh
$ make run                                                                                                                                                                         
Creating kernel.elf...
ld: unknown option: -T
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/_me_/Dev/repos/experiments/os-crystal/kernel.elf' -nostdlib -m32 -Wl,-T,/Users/_me_/Dev/repos/experiments/os-crystal/src/link.ld,--build-id=none -rdynamic  -L/usr/lib -L/usr/local/lib`
make: *** [kernel.elf] Error 1
```

Could you please help?

**Comment by refi64** [comment]
Not the dev, but AFAIK this uses linker scripts and features that only work on platforms that use the ELF binary format, e.g. Linux and the BSDs.

**Comment by lbguilherme** [comment]
It only builds on Linux with the packages `qemo`, `grub2-mkrescue`, and `xorriso`. I just tested it in my machine and it builds fine. But for some reason it fails to run, probably I messed up with my environment.

I don't plan to support new features here, but I'll make it work and improve the information o the Readme to at least explain how to run it.

**Comment by veelenga** [comment]
Thanks a lot 👍
